# Generated by Django 5.1.4 on 2026-01-09 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Plataforma')),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('domain', models.CharField(max_length=255, verbose_name='Dominio')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de Contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Configuracion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='ID Externo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(blank=True, max_length=20, verbose_name='Cedula')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Direccion')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='platforms.platform')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, verbose_name='ID Externo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='platforms.platform')),
            ],
            options={
                'verbose_name': 'Usuario de Plataforma',
                'verbose_name_plural': 'Usuarios de Plataformas',
                'ordering': ['-created_at'],
                'unique_together': {('platform', 'external_id')},
            },
        ),
    ]
