# Generated by Django 5.1.4 on 2026-01-09 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('specialty', models.CharField(choices=[('cobranzas', 'Cobros de Peso'), ('embargos', 'Embargos'), ('intimaciones', 'Intimaciones'), ('general', 'Asuntos Generales')], default='general', max_length=20)),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_on_shift', models.BooleanField(default=False, verbose_name='En Turno')),
                ('max_concurrent_cases', models.PositiveIntegerField(default=5, verbose_name='Max Casos Simultaneos')),
                ('total_cases_handled', models.PositiveIntegerField(default=0, verbose_name='Casos Atendidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abogado',
                'verbose_name_plural': 'Abogados',
                'ordering': ['-is_on_shift', '-is_available', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LawyerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='Dia')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('lawyer', 'day_of_week')},
            },
        ),
    ]
