# Generated by Django 5.1.4 on 2026-01-09 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='ID Externo del Prestamo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del Prestamo')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance Pendiente')),
                ('currency', models.CharField(default='DOP', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('al_dia', 'Al Dia'), ('retraso', 'Retraso'), ('mora', 'Mora'), ('vencido', 'Vencido'), ('cobranza', 'Cobranza'), ('legal', 'Legal'), ('reestructurado', 'Reestructurado'), ('saldado', 'Saldado')], default='retraso', max_length=20)),
                ('days_overdue', models.PositiveIntegerField(default=0, verbose_name='Dias en Atraso')),
                ('payment_history', models.JSONField(blank=True, default=list, verbose_name='Historial de Pagos')),
                ('full_data', models.JSONField(blank=True, default=dict, verbose_name='Datos Completos')),
                ('loan_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Prestamo')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='platforms.client')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'ordering': ['-days_overdue', '-created_at'],
            },
        ),
    ]
