# Generated by Django 5.1.4 on 2026-01-09 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_case', 'Nuevo Caso'), ('new_message', 'Nuevo Mensaje'), ('case_assigned', 'Caso Asignado'), ('case_closed', 'Caso Cerrado'), ('reminder', 'Recordatorio')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('both', 'Ambos')], default='both', max_length=10)),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='conversations.conversation')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
