# Generated by Django 5.1.4 on 2026-01-09 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyers', '0001_initial'),
        ('loans', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('waiting_client', 'Esperando Cliente'), ('waiting_lawyer', 'Esperando Abogado'), ('resolved', 'Resuelta'), ('closed', 'Cerrada')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Asunto')),
                ('procedure_requested', models.CharField(blank=True, max_length=100, verbose_name='Procedimiento Solicitado')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolucion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='platforms.client')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='lawyers.lawyer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='loans.loan')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='platforms.platform')),
                ('platform_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='platforms.platformuser')),
            ],
            options={
                'verbose_name': 'Conversacion',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('platform_user', 'Usuario de Plataforma'), ('lawyer', 'Abogado'), ('system', 'Sistema')], max_length=20)),
                ('sender_id', models.UUIDField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(verbose_name='Contenido')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('is_system_message', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['sent_at'],
            },
        ),
    ]
