# Generated by Django 5.1.4 on 2026-01-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='page_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de Origen'),
        ),
    ]
